function [tip_nose,waveform,nose_adapt]=adaptive_whisking_controlled_simulation (t_start,init_phase,f_free,ret_free,pro_free,no_whisk,midline_angle,adapt_factor,duty_factor,ampl_mod_factor,caudal_dist,whisker_length,single_touch_dur)

%% example
%[tip_nose,waveform,nose_adapt]=adaptive_whisking_controlled_simulation(0,0.1,10,30,30,8,13,5.3,.1,0.04,9,4,30);
% waveform first column keeps the time, the second column keeps the angular
% position in relation to midline of whisker, the third and fourth columns
% contain the alpha of the fitted parabola and x position of the whisker's tip
% respectively, and finally the fifth column keeps the whisker's tip distance to
% target

%% suggested values for C2 whisker
% t_start=0; starting time
% init_phase=0;
% f_free=10;%Hz  free whisking frequency
% ret_free=23;  maxium retraction anngle relative to midline in free whisking
% por_free=23; maxium protraction anngle relative to midline in free whisking
% no_whisk=8;  total number of whisk
% midline_angle=15;   the angle between the midline the whisker swings
% around and the line perpendicular to the face at the whisker's base
% adapt_factor=3.5; adaptation factor: angle increase/decrease in case of
% adaptation for each whisk
% duty_factor=0.15; adaptation factor: the increse in duty cycle in case of adaptation
%ampl_mod_factor=0.055;  amplitude modulation factore
%caudal_dist=9; the caudal distance between the nose and the base of the
%whisker

[waveform,adapt_flag,no_free_whisk,nose_adapt,nose_non_adapt]=Initialize;

%whisking
for it=1:no_whisk
    
    %% Retraction from midpoint: M1 modulates whisking pattern generated by CPG represented in this module by sinosoid
    
    [adapt,f,amp_mod,no_free_whisk,t_start,t_cont,t,angle_ret]=M1_ret(t_start,init_phase,no_free_whisk,adapt_flag,adapt_factor,it,ampl_mod_factor,f_free,ret_free);
 
    last=length(waveform(:,1)); % save waveforms
    waveform([last+1:last+length(t)],1)=t_cont;% save waveforms
    waveform([last+1:last+length(t)],2)=angle_ret;% save waveforms
    t_start=t_start+(1/(2*f));% save waveforms
    
    %% pProtraction from midpoint: M1 modulates whisking pattern generated by CPG represented in this module by sinosoid
    
    [adapt,f,amp_mod,no_free_whisk,t_start,t_cont,t,angle_pro]=M1_pro(t_start,init_phase,adapt_flag,it,no_free_whisk,adapt_factor,ampl_mod_factor,duty_factor,f_free,pro_free);
    
    last=length(waveform(:,1));% save waveforms
    waveform([last+1:last+length(t)],1)=t_cont;% save waveforms
    waveform([last+1:last+length(t)],2)=smooth(angle_pro,20);% save waveforms
    t_start=t_start+(1/(2*f));% save waveforms
    
    %% Translate M1 into whisker movement
    
    [waveform,nose_adapt,tip_nose]=Superior_Colliculus(waveform,midline_angle,whisker_length,ret_free,nose_adapt,caudal_dist);
    
    %% sensation and adaptive whisker retraction
    
    [adapt_flag,waveform,t_start]=S1(tip_nose,single_touch_dur,waveform,t_start,f,adapt_flag);
    
end

%% waeforms ready to plot
clear tip_nose
tip_nose=-smooth(waveform(:,5))*10+nose_adapt(1:length(waveform(:,5)))+caudal_dist;

waveform(:,2)=smooth(waveform(:,2),20);
waveform(:,6)=nose_adapt(1:length(waveform(:,1)),1);

%% plots

figure;
waveform(:,2)=smooth(waveform(:,2));

hold on
plot(waveform(:,1),waveform(:,2),'b') % angular
title('angular position');xlabel('Time(s)');ylabel('Deflection angle (deg)');
waveform(:,5)=smooth(waveform(:,5));

figure
hold on
plot(waveform(:,1),waveform(:,5),'b'); % tip position
title('Tip position from base');xlabel('Time(s)');ylabel('position (cm)');
tip_nose=-smooth(waveform(:,5))*10+waveform(:,6)+caudal_dist; % 9 for caudal distance between the nose and the whisker

figure
plot(waveform(:,1),tip_nose,'b'); % tip position
title('Tip position to target');xlabel('Time(s)');ylabel('Distance to target (mm)');
hold on
plot (waveform(:,1),waveform(1:length(waveform(:,5)),6),'r')
plot (waveform(:,1),zeros(1,length(waveform(:,5))),'k')
